# Generated by Django 5.2.8 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('delivery_type', models.CharField(max_length=30)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.FloatField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
