# Generated by Django 5.2.8 on 2025-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='estimate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='In transit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='delivery_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
