# Generated by Django 5.2.8 on 2025-11-21 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_shipment_current_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-last_update']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='dimensions',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(default='Standard', max_length=80),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('PICKUP', 'Pickup'), ('PROCESSED', 'Processed'), ('DEPARTED', 'Departed'), ('ARRIVED', 'Arrived'), ('CLEARANCE', 'Customs Clearance'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('facility', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
